### ISSUE TITLE
AssertionError: assert len(label_class) > 0 failed

### ISSUE THREAD

**Issue by RogerQi** [Sam1224/SCCAN#5]
I followed the provided instructions to download the model checkpoints and prepared the data folder as organized. I tried to use the provided base models to reproduce the results in the paper. However, The evaluation script failed shortly after a few iterations.

Here is the command line I used to invoke the evaluation process

```bash
(sccan) ➜  SCCAN git:(master) ✗ python test_sccan.py --config=config/pascal/pascal_split2_resnet101.yaml
```

Here is the generated output.

```
[2023-11-11 12:04:07,635 INFO test_sccan.py line 254 22439] Test: [200/1000] Data 0.003 (0.005) Batch 0.111 (0.117) Remain 00:01:33 Loss 0.7433 (0.9561) Accuracy 0.9135.
[2023-11-11 12:04:08,765 INFO test_sccan.py line 254 22439] Test: [210/1000] Data 0.003 (0.005) Batch 0.112 (0.117) Remain 00:01:32 Loss 0.2042 (0.9433) Accuracy 0.9357.
Traceback (most recent call last):
  File "test_sccan.py", line 294, in <module>
    main()
  File "test_sccan.py", line 150, in main
    fb_iou, miou, piou = validate(val_loader, model, val_seed, args.split)
  File "test_sccan.py", line 209, in validate
    for i, (input, target, s_input, s_mask, subcls, ori_label) in enumerate(val_loader):
  File "/home/roger/anaconda3/envs/sccan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/roger/anaconda3/envs/sccan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/roger/anaconda3/envs/sccan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/roger/anaconda3/envs/sccan/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/home/roger/anaconda3/envs/sccan/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/roger/anaconda3/envs/sccan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/roger/anaconda3/envs/sccan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/roger/reproduction/SCCAN/util/dataset.py", line 229, in __getitem__
    assert len(label_class) > 0
AssertionError
```

I looked into this file. It seemed to have something to do with the segmentation masks, which I am not sure how to resolve.

Did you do any pre-processing for masks in the SegmentationClassAug folder? Would you mind sharing your processed Pascal dataset?

**Comment by Sam1224** [comment]
Hi, sorry for the late response and thank you for your interests in our work. I previously downloaded pascal directly from PFENet's repo. I just uploaded pascal to OneDrive and you can download via: https://entuedu-my.sharepoint.com/:u:/g/personal/qianxion001_e_ntu_edu_sg/EY3CDbNGWYhGtNslXshuTRkB9qqdmziXhALNsjIvFKjr6g

**Comment by RogerQi** [comment]
Thanks. I just tested these to be working on my machine.

Thank you for your reply and congrats on the great work! I am closing the issue for now.
